name = "NonnegativityPositiveOrthant"
uuid = "f97b99a9-d0d9-42f0-bec9-82415b5ab1cb"
authors = ["Elisenda Feliu, Joan Ferrer and Máté Telek"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
