name = "NonnegativityPositiveOrthant"
uuid = "f97b99a9-d0d9-42f0-bec9-82415b5ab1cb"
authors = ["Elisenda Feliu, Joan Ferrer and Máté Telek"]
version = "1.0.0-DEV"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
